// <auto-generated />
using System;
using Manager.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Manager.Infra.Migrations
{
    [DbContext(typeof(ManagerContext))]
    [Migration("20211220212536_RelacionamentoMigration")]
    partial class RelacionamentoMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Manager.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .UseIdentityColumn();

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ativo");

                    b.Property<float>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("FLOAT(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("nome");

                    b.Property<float>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("FLOAT(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("TB_CLIENTE");
                });

            modelBuilder.Entity("Manager.Domain.Entities.Funcionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .UseIdentityColumn();

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("dtAlteracao");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("dtCadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("TB_FUNCIONARIO");
                });

            modelBuilder.Entity("Manager.Domain.Entities.Relacionamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .UseIdentityColumn();

                    b.Property<long>("ClienteId")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("DtConclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtConclusao");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtInicio");

                    b.Property<DateTime>("DtRetorno")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtRetorno");

                    b.Property<string>("Finalizado")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("finalizado");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("observacao");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("TB_RELACIONAMENTO");
                });

            modelBuilder.Entity("Manager.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR(180)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("TB_USER");
                });

            modelBuilder.Entity("Manager.Domain.Entities.Relacionamento", b =>
                {
                    b.HasOne("Manager.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Relacionamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manager.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany("Relacionamentos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Manager.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Relacionamentos");
                });

            modelBuilder.Entity("Manager.Domain.Entities.Funcionario", b =>
                {
                    b.Navigation("Relacionamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
